// # Proxy Compiler 18.9.3-e21ac4-20181026

import Foundation
import SAPOData

internal class YMSESAPPROVALSRVEntitiesStaticResolver {
    static func resolve() {
        YMSESAPPROVALSRVEntitiesStaticResolver.resolve1()
    }

    private static func resolve1() {
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.notification)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.subscription)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.ymSesIosApprove)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.ymSesIosCreate)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.ymSesIosItems)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.ymSesIosSearhHelp)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntityTypes.ymSesIosView)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.notificationCollection)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.subscriptionCollection)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.ymSESIOSAPPROVESet)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.ymSESIOSCREATESet)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.ymSESIOSITEMSSet)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.ymSESIOSSEARHHELPSet)
        Ignore.valueOf_any(YMSESAPPROVALSRVEntitiesMetadata.EntitySets.ymSESIOSVIEWSet)
        Ignore.valueOf_any(Notification.id)
        Ignore.valueOf_any(Notification.collection)
        Ignore.valueOf_any(Notification.title)
        Ignore.valueOf_any(Notification.updated)
        Ignore.valueOf_any(Notification.changeType)
        Ignore.valueOf_any(Notification.entriesOfInterest)
        Ignore.valueOf_any(Notification.recipient)
        Ignore.valueOf_any(Subscription.id)
        Ignore.valueOf_any(Subscription.user)
        Ignore.valueOf_any(Subscription.updated)
        Ignore.valueOf_any(Subscription.title)
        Ignore.valueOf_any(Subscription.deliveryAddress)
        Ignore.valueOf_any(Subscription.persistNotifications)
        Ignore.valueOf_any(Subscription.collection)
        Ignore.valueOf_any(Subscription.filter)
        Ignore.valueOf_any(Subscription.select)
        Ignore.valueOf_any(Subscription.changeType)
        Ignore.valueOf_any(YmSesIosApprove.lblni)
        Ignore.valueOf_any(YmSesIosApprove.sesTxz01)
        Ignore.valueOf_any(YmSesIosApprove.sbnamag)
        Ignore.valueOf_any(YmSesIosApprove.ernam)
        Ignore.valueOf_any(YmSesIosApprove.lwert)
        Ignore.valueOf_any(YmSesIosApprove.lbldt)
        Ignore.valueOf_any(YmSesIosApprove.bsart)
        Ignore.valueOf_any(YmSesIosApprove.lifnr)
        Ignore.valueOf_any(YmSesIosApprove.ebeln)
        Ignore.valueOf_any(YmSesIosApprove.ebelp)
        Ignore.valueOf_any(YmSesIosApprove.poTxzo1)
        Ignore.valueOf_any(YmSesIosApprove.netpr)
        Ignore.valueOf_any(YmSesIosApprove.wiID)
        Ignore.valueOf_any(YmSesIosApprove.appFlag)
        Ignore.valueOf_any(YmSesIosApprove.eindt)
        Ignore.valueOf_any(YmSesIosApprove.netCurr)
        Ignore.valueOf_any(YmSesIosApprove.poCurr)
        Ignore.valueOf_any(YmSesIosApprove.headToItems)
        Ignore.valueOf_any(YmSesIosApprove.ymSESIOSITEMSSet)
        Ignore.valueOf_any(YmSesIosCreate.sheetNo)
        Ignore.valueOf_any(YmSesIosCreate.personInt)
        Ignore.valueOf_any(YmSesIosCreate.shortText)
        Ignore.valueOf_any(YmSesIosCreate.poNumber)
        Ignore.valueOf_any(YmSesIosCreate.poItem)
        Ignore.valueOf_any(YmSesIosCreate.note)
        Ignore.valueOf_any(YmSesIosItems.extrow)
        Ignore.valueOf_any(YmSesIosItems.ebeln)
        Ignore.valueOf_any(YmSesIosItems.menge)
        Ignore.valueOf_any(YmSesIosItems.tbtwr)
        Ignore.valueOf_any(YmSesIosItems.waers)
        Ignore.valueOf_any(YmSesIosItems.netwr)
        Ignore.valueOf_any(YmSesIosItems.ktext1)
        Ignore.valueOf_any(YmSesIosItems.packno)
        Ignore.valueOf_any(YmSesIosItems.introw)
        Ignore.valueOf_any(YmSesIosSearhHelp.ebeln)
        Ignore.valueOf_any(YmSesIosSearhHelp.ebelp)
        Ignore.valueOf_any(YmSesIosView.sesTxz01)
        Ignore.valueOf_any(YmSesIosView.lblni)
        Ignore.valueOf_any(YmSesIosView.sbnamag)
        Ignore.valueOf_any(YmSesIosView.ernam)
        Ignore.valueOf_any(YmSesIosView.lwert)
        Ignore.valueOf_any(YmSesIosView.lbldt)
        Ignore.valueOf_any(YmSesIosView.bsart)
        Ignore.valueOf_any(YmSesIosView.lifnr)
        Ignore.valueOf_any(YmSesIosView.ebeln)
        Ignore.valueOf_any(YmSesIosView.ebelp)
        Ignore.valueOf_any(YmSesIosView.poTxzo1)
        Ignore.valueOf_any(YmSesIosView.netpr)
        Ignore.valueOf_any(YmSesIosView.wiID)
        Ignore.valueOf_any(YmSesIosView.eindt)
        Ignore.valueOf_any(YmSesIosView.netCurr)
        Ignore.valueOf_any(YmSesIosView.poCurr)
        Ignore.valueOf_any(YmSesIosView.viewheadToItems)
    }
}
